- repo: https://github.com/prettier/prettier
  rev: '1.18.2'
  hooks:
    - id: prettier
      args: [--config, ./ESSArch_Core/frontend/static/frontend/.prettierrc]

- repo: https://github.com/timothycrosley/isort
  rev: '4.3.21'
  hooks:
    - id: isort
      args: [--filter-files]
