- repo: https://github.com/prettier/prettier
  rev: "1.16.4"
  hooks:
    - id: prettier

- repo: https://github.com/pre-commit/mirrors-isort
  rev: "v4.3.21"
  hooks:
    - id: isort

- repo: https://gitlab.com/pycqa/flake8
  rev: "3.7.8"
  hooks:
    - id: flake8
