version: "3.3"

services:
  essarch:
    image: essarch
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL_ESSARCH: postgres://arkiv:password@db:5432/essarch
      REDIS_URL_ESSARCH: redis://redis/1
      RABBITMQ_URL_ESSARCH: amqp://guest:guest@rabbitmq:5672
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ..:/code
      - ./data:/ESSArch/data
      - ./config:/ESSArch/config
      - ./log:/ESSArch/log
      - /code/ESSArch_Core/frontend/static/frontend/node_modules
    command:
      - /bin/bash
      - -c
      - |
        /code/docker/wait_for.sh db 5432
        /code/docker/wait_for.sh redis 6379
        /code/docker/wait_for.sh rabbitmq 5672
        /code/docker/wait_for.sh elasticsearch 9200
        /code/docker/docker-entrypoint.sh
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db
      - rabbitmq
      - redis
      - elasticsearch
    networks:
      - essarch

  worker:
    image: essarch
    command:
      - /bin/bash
      - -c
      - |
        /code/docker/wait_for.sh redis 6379
        /code/docker/wait_for.sh rabbitmq 5672
        /code/docker/wait_for.sh essarch 8000
        /code/docker/wait_for.sh elasticsearch 9200
        celery -A config worker -l info -Q celery,file_operation,validation
    environment:
      DATABASE_URL_ESSARCH: postgres://arkiv:password@db:5432/essarch
      REDIS_URL_ESSARCH: redis://redis/1
      RABBITMQ_URL_ESSARCH: amqp://guest:guest@rabbitmq:5672
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ..:/code
      - ./data:/ESSArch/data
      - ./config:/ESSArch/config
      - ./log:/ESSArch/log
      - /code/ESSArch_Core/frontend/static/frontend/node_modules
      - /code/ESSArch_Core/frontend/static/frontend/build
    tty: true
    depends_on:
      - essarch
      - rabbitmq
      - redis
      - elasticsearch
    networks:
      - essarch

  beat:
    image: essarch
    command:
      - /bin/bash
      - -c
      - |
        /code/docker/wait_for.sh redis 6379
        /code/docker/wait_for.sh rabbitmq 5672
        /code/docker/wait_for.sh essarch 8000
        /code/docker/wait_for.sh elasticsearch 9200
        celery -A config beat -l info
    environment:
      DATABASE_URL_ESSARCH: postgres://arkiv:password@db:5432/essarch
      REDIS_URL_ESSARCH: redis://redis/1
      RABBITMQ_URL_ESSARCH: amqp://guest:guest@rabbitmq:5672
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ..:/code
      - ./data:/ESSArch/data
      - ./config:/ESSArch/config
      - ./log:/ESSArch/log
      - /code/ESSArch_Core/frontend/static/frontend/node_modules
      - /code/ESSArch_Core/frontend/static/frontend/build
    tty: true
    depends_on:
      - essarch
      - rabbitmq
      - redis
      - elasticsearch
    networks:
      - essarch

  db:
    image: "postgres"
    environment:
      POSTGRES_DB: essarch
      POSTGRES_USER: arkiv
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - essarch

  redis:
    image: "redis"
    networks:
      - essarch
    ports:
      - 6379:6379

  rabbitmq:
    image: "rabbitmq"
    ports:
      - 5672:5672
    networks:
      - essarch

  elasticsearch:
    build:
      context: elasticsearch
      args:
        ELK_VERSION: 6.5.4
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - essarch

networks:
  essarch:
    driver: bridge
